# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jgKyG3ck6thjDNS_-YN45POgiKM6ij12

**Installing required Libraries.**
"""

pip install google-api-python-client

"""**Importing required Libraries.**"""

from googleapiclient.discovery import build
import pandas as pd

"""**Enter Youtube API details to build connection.**"""

youTubeApikey="AIzaSyDnPxOIV20GYpe8Vp0Ru2nO0qYQA0qgSZ8"
youtube=build('youtube','v3',developerKey=youTubeApikey)

"""**Creating a request to scrape required details for the given video ids.**"""

request=youtube.videos().list(
        part="statistics,contentDetails,snippet",
        id="Ks-_Mh1QhMc,N80jTRvZbhw,5kAtCrFJT9w,kmXPA3xyxiQ,CXMAXD3rDGc,YuQd2m-teUc,Fqmn_K2gRIA,F8_QrWfnGCo,WTJSt4wP2ME,5Yhf0wBFtvY"
    )

"""**Excecuting the request to get a response**"""

response=request.execute()

"""**Creating a structure which will be converted into a Dataframe**"""

parser={'video_id' :[i['id'] for i in response['items']],
        'title' : [i['snippet']['title'] for i in response['items']],
        'Publish_date' : [i['snippet']['publishedAt'] for i in response['items']],
        'likes':[i['statistics']['likeCount'] for i in response['items']],
        'views':[i['statistics']['viewCount'] for i in response['items']]}

"""**Creating a Dataframe of the required details.**"""

df=pd.DataFrame(parser)

"""**Converting the published date column into a proper format.**"""

import datetime
df['Publish_date'] = pd.to_datetime(df['Publish_date']).dt.date

"""**Printing the Final Dataframe.**"""

df

df.to_csv("assignment.csv")

